from backendLoanAssessment.models.UserModel import UserModel
from backendLoanAssessment.models.LoanApplicationModel import LoanApplicationModel
from backendLoanAssessment.models.ApplicationResultsModel import ApplicationResultModel